### ISSUE TITLE
Test NPOT framebuffer code

### ISSUE THREAD

**Issue by rbuch703** [OSMBuildings/OSMBuildings#74] opened 2016-04-13 09:23 UTC
I created the "NPOT framebuffer" branch where framebuffer textures are no longer required to have power-of-two width and height. This has a few advantages:
- should reduce memory required for framebuffers quite a bit (statistically by more than 50%)
- reduces code size
- get's rid of the thin red lines at the top and right view edges

NPOT textures have a few limitations in WebGL/GLES (texCoords must be `CLAMP_TO_EDGE`'d and they cannot be mipmapped, so texture filtering based on mipmaps does not work), but those are not relevant to our framebuffers.

Anyway, the code seems to work as intended on my desktop PC and tablet (Nexus 7 2012), but should be tested on more mobile devices before merging into develop.

**Comment by kekscom** [comment] 2016-04-13 09:55
BTW Reminds me that we could setup a test environment where branches get deployed to.

I'll check the NPOT changes on OSX, Win7, Android and iOS.

**Comment by kekscom** [comment] 2016-04-13 12:24
- [X] OSX Chrome
- [X] OSX Safari
- [X] Cheapo Android Tablet
- [ ] iOS - heavy Moire, see screenshot
- [X] Win7 Chrome
- [ ] Win7 MSIE 11 - No display, "Depth Textures not supported". Even on current prod version. Yes, t's an old PC

iOS
![2016-04-13 14 03 21](https://cloud.githubusercontent.com/assets/1887727/14492848/4c17ab80-0182-11e6-8fbf-68222c5dc08b.png)

**Comment by kekscom** [comment] 2016-04-13 12:26
Too bad because I like the changes.
At least iOS should be fixed.

For Windows maybe Edge should be the reference.

**Comment by rbuch703** [comment] 2016-04-13 19:27
We'll, the MSIE error is probably unrelated; the reason for the error is more likely #76.

The iOS bug is strange, though. Depth/shadow resolution shouldn't be affected by the change. I'll try to look into it, but I don't have any iOS devices to work with.

**Comment by kekscom** [comment] 2016-04-13 21:56
Yes, MSIE is likely #76 Just found it now.

For iOS, would it make sense to get you a test device?
Will be difficult anyway as you won't get debugging without a Mac.
But for quick tests it might be fine.
If the issue persists, we could do some testing together with my hardware.

**Comment by wallb** [comment] 2016-04-16 22:58
I had a look at the npotFramebuffers branch on an iPhone 5S and iPad3. Didn't see the heavy moire until I remembered that the current time is used if setDate is not called explicitly. When adding `osmb.setDate(new Date(2016, 4, 16, 12, 0, 0));` I saw the artefacts (similar to kekscom's screenshot) on the iPhone 5S (A7 GPU), but not on the iPad3 (PowerVR SGX 543).

I could make the shadow artefacts go away by having
```
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
```
at the top of basemap.shadows.fs and buildings.shadows.fs. It is strange though, that the 5S showed severe artefacts while the iPad3 and the Android tablet didn't. There were some barely noticeable artefacts within the shadow areas on the iPad3. These also seemed to be fixed when using highp.

**Comment by kekscom** [comment] 2016-04-17 09:27
Interesting. I can confirm on iPad4 it's fine!
Heavy Moire only on iPhone 5s.

**Comment by kekscom** [comment] 2016-04-17 11:31
Well I wasn't aware live version is affected by the Moire as well.
Then it's not related to NPOT, but fix is urgent.

**Comment by rbuch703** [comment] 2016-04-17 19:10
So it seems the iOS issue is unrelated to the NPOT framebuffers (and I just saw that @kekscom fixed it in any case). Does that mean we can merge the NPOT framebuffer code into `develop`?

**Comment by kekscom** [comment] 2016-04-17 19:31
Is it ok from your side to have those shader precision modified? (no bad impact?)
For NPOT, please merge.

**Comment by rbuch703** [comment] 2016-04-18 11:04
Ok, NPOT framebuffers are merged into `develop`. And the iOS issue on iPhone 5s should be gone. Can we close this issue?

**Comment by kekscom** [comment] 2016-04-18 21:13
Working fine.

**Comment by kekscom** [comment] 2016-06-29 05:37
Whatever happened, but heavy Moire is back on iOS. Feels worse than before.

As code didn't really change meanwhile, I might have broken the build process or an iOS/iPhone update is causing this.

Now Using iOS 9.3.2 on iPhone SE

Can anyone confirm?

**Comment by kekscom** [comment] 2019-07-06 13:10
Still an issue but we're going to solve this in a different stack.

**Closed by kekscom** 2019-07-06 13:10 UTC
