### ISSUE TITLE
Support highlighting multiple features

### ISSUE THREAD

**Issue by dkniffin** [OSMBuildings/OSMBuildings#61] opened 2016-04-08 17:01 UTC
I would like to be able to highlight more than one building/object.

I'm going to take a stab at implementing this, but I'll have some questions. I'll put them here as I have them. 

My first question: what does [this function](https://github.com/OSMBuildings/OSMBuildings/blob/master/src/render/Picking.js#L87) do? The name seems to indicate it converts an id to a color. Is that right? I'm not sure I understand what that accomplishes.

**Comment by kekscom** [comment] 2016-04-08 21:15
Correct spatial picking is done by assigning a color to each object.
These are rendered invisibly and stored.
Once you click at x/y, color is retrieved and then you know the object.

The mentioned function creates such color for a given object id.

**Comment by dkniffin** [comment] 2016-04-08 21:31
Oh, I see. Huh. That's an interesting way to do it.

**Comment by rbuch703** [comment] 2016-04-09 15:24
@dkniffin note that statically highlighting multiple buildings is already possible in OSMBuildings through modifiers. See `test/index.html` for examples, especially the function `colorLandmarks()`.

**Comment by dkniffin** [comment] 2016-04-09 16:15
Hmm. So, it looks like that function would be passed to `addGeoJSONTiles` as `modifier`. Is that right?

I'm not sure if this will do what I want or not. I want to be able to click on a building (or object), and have it be highlighted, but also keep the functionality of highlighting buildings on hover. Maybe even do them in different colors.

**Comment by rbuch703** [comment] 2016-04-09 16:55
> So, it looks like that function would be passed to addGeoJSONTiles as modifier. Is that right?

Yes, exactly. But seeing more clearly what you are trying to do, this mechanism unfortunately won't help you as is. The modifier is called for every building only exactly once, at the time its 3D geometry is created from the GeoJSON data. There is currently no mechanism to change the modifier and re-apply it to the buildings already loaded.

**Comment by kekscom** [comment] 2016-04-09 17:33
But there is also filters mechanism in place. Right now this allows dynamically show/hide of given buildings. This could be modified to support colors as well. Perhaps a replacement even for the initial modifier.

**Comment by dkniffin** [comment] 2016-04-11 14:34
@kekscom to do a filter like you're mentioning, would I add two layers? One just for displaying the selected building, and the other for displaying all the rest of the buildings? And then style each differently?

**Comment by kekscom** [comment] 2016-04-11 18:15
Right back.
I was referring to show() / hide() methods. Both accept a selector function plus a duration value.
Internally we have a GL property for 'degree of visibility' which maps to height actually.
As result, you can toggle buildings (optionally) with some timeline based animation.

Now, this could be enhanced to modify colors.

See:
https://github.com/OSMBuildings/OSMBuildings/blob/master/src/Filter.js
https://github.com/OSMBuildings/OSMBuildings/blob/master/src/mesh/GeoJSON.js
https://github.com/OSMBuildings/OSMBuildings/blob/master/src/mesh/OBJ.js

To make things complicated, it's designed as hide() : 'add a "hidden" filter', show() : 'remove that "hidden" filter'.
That way it was easier to handle not yet loaded matching objects and multiple rulesets.

HTH

**Comment by kekscom** [comment] 2016-04-11 18:23
I'd love to see something like a combination of this and the initial modifier @rbuch703 mentioned.

**Comment by elcinertugrul** [comment] 2016-05-06 22:17
@kekscom @rbuch703 
I couldn't make the modifier work. Are u using OSMBuildings-GLMap.js from "Improved calculation of visible tiles" release from https://github.com/OSMBuildings/OSMBuildings/releases

I have been doing a mini hack by myself and been trying to bind a custom geojson data into OSMbuildings! one of the properties of the input data  is identical with one of the properties of osm object!  Initial goal is to render osmbuildings with color-coded per one of the input properties. I think the modifier function is the solution but i have passed a simple modifier as in the example but no luck!

Could u please advice me ? Thank you

**Comment by rbuch703** [comment] 2016-05-08 09:15
@elcinertugrul Judging from the changelog message you posted (`"Improved calculation of visible tiles"`), you are using OSMBuildings `2.0.0` from October of last year. The ability to use modifiers was introduced quite a bit later, in version `2.4.1` (April 18, 2016). So you'll have to update your version of OSMBuildings to at least `2.4.1` to be able to use modifiers.

**Comment by elcinertugrul** [comment] 2016-05-09 14:14
Thank you @rbuch703 for quick reply! I tried your simple test w/ modifiers and works like a charm. 

I am interested in a unique tag of OSMbuildings. I was wondering the returning properties with modifiers are the same the one returns from overpass api ? 

![image](https://cloud.githubusercontent.com/assets/3409121/15115517/5d01d3b2-15cd-11e6-86f1-f8a2ecfd820d.png)

The overpass api the tag is as shown at snapshot above "nycdoitt:bin"

I am not sure the syntax of this property, but I ran a few tests they throw a following errors.
**properties.nycdoitt:bin** Uncaught Syntax Error: Unexpected token,
or 
**properties.nycdoitt.bin**  Uncaught TypeError: Cannot read property 'bin' of undefined

Do u know what I am missing here ? Thank you very much.

**Comment by rbuch703** [comment] 2016-05-09 14:31
OSMBuildings takes its data from an Overpass server, but filters it. Most attributes are thrown away; only a few building-related attributes are kept, and in some cases merged and renamed. Your `nycdoitt:bin` is one of the many that get removed. The documentation on which OSM attributes are kept and what they have been renamed to can be found at https://github.com/OSMBuildings/OSMBuildings/blob/master/docs/server.md .

But if you are only looking for any unique identifier you're in luck: your modifier function already gets called with an `id` in addition to the set of `properties`. That `id` is the way/relation id from OSM, the same that Overpass returns. It is mostly unique (there can be at most a single other object in OSM worldwide that shares the same ID), so it might be usable for your purposes.

**Comment by elcinertugrul** [comment] 2016-05-09 19:12
Thank you @rbuch703, good to know. if we could get all the attributes in overpass into object's properties would be fantastic. I could send html request to get all the tags and parse json but this would be just repetition. But I have also noticed not all of the osm buildings in NYC has the "nycdoitt:bin" attributes in overpass api.  I think previous server used to returned more data than overpass API. I used to send request using this url:
'http://data.osmbuildings.org/0.2/rkc8ywdl/feature/'+OSMID +'.json'

I will look around for another solution to bind the external geojson data to osm webgl, may be using lat and long values... 

Thank you for your answers,

**Comment by kekscom** [comment] 2016-05-09 21:02
@elcinertugrul the feature query URL you mentioned is not a core function of OSM Buildings.
Also adding all source properties to all features is not in scope.

But it's very valid to mash up with Overpass here.
You might even leave out geometry and filter for features that really contain nytdoitt:bin.

Side note: the property might be gone after several edits in OSM.

**Comment by sevamoo** [comment] 2016-05-13 21:14
@elcinertugrul @rbuch703 @kekscom 
Hi 
Thanks for the super cool library. I have similar problem to this issue. I am wondering what would be the best strategy if I want to colorcode all the buildings based on another source than OSM. Of course, there will be a unique key such as OSM ID. 
As a possible scenario, I am interested to color buildings based on their distances to public transport, assuming that these distances are precomputed. 
Thanks a lot for your feedbacks.

**Comment by rbuch703** [comment] 2016-05-14 07:32
@sevamoo: Here's how I build a similar solution:

(note that since my last post in this thread, @kekscom has kindly implemented feature request #88 on the server side, so building IDs are now unique.)

1. Convert your `other` data source to a mapping (e.g. a JavaScript object) between the OSM way/relation IDs of each building and your additional attribute (e.g. your distance or time to public transportation). Its important to prefix each building ID with a `w` or `r` depending on whether the building is based on an OSM *way* or a OSM *relation*, because the IDs themselves are not unique without that information (any other way to distinguish between way and relations would be fine, too; but the `w`/`r` prefixes is what the OSMBuildings GeoJSON tiles will return, so matching will be easier if you follow the same approach). Save this mapping as a single JSON file for your whole data set. 
2. On your web page, 
  1. create and OSMBuildings GLMap and add a basemap layer, but **do not** add the *building* layer just yet.
  2. Let JavaScript start downloading your JSON file that contains the mapping created in the first step, via AJAX/XmlHttpRequest.
  3. Once the mapping has been downloaded let your browser parse it to yield a JavaScript object, and bind that object to a global variable. 
  4. Now create a `modifier` method to color the buildings. This will probably be similar to https://github.com/OSMBuildings/OSMBuildings/blob/b29094e4242650cfc7e2eeb80986dc5a0788edf7/test/index.html#L162-L185 , only that your mapping will not be hardcoded like the list of `landmarkIDs` in this example, but will come from the global object you created in the step above. Note that the example code is slightly outdated, since the landmark IDs are not yet prefixed with `w`/`r`.
  5. Now, add the building layer to your GLMap, and tell it to use your `modifier` to color the buildings, as in https://github.com/OSMBuildings/OSMBuildings/blob/b29094e4242650cfc7e2eeb80986dc5a0788edf7/test/index.html#L191

This should make each building have the color you gave it in your modifier.

**Comment by sevamoo** [comment] 2016-05-14 07:59
@rbuch703 Thanks a lot for this precise guideline. I will go through it and will come back later. 
However, I have still one concern that is the scalability. Maybe this will be out of scope here, but I am thinking to do this coloring for large number of buildings, let say for a whole country like Switzerland. You think in this scale still it is valid to think about making a separate JSON file? Sorry, as my Java scripting knowledge is basic.
My other scenario was to develop a modified OSM data source (including other features e.g. distance to public transport) and using something like Tangram and Vector files.
Best
Vahid

**Comment by kekscom** [comment] 2016-05-14 11:41
Hi Vahid,
Whoever has a running example of this implementation should add it to our documentation.
For scalability, this is not an ideal solution. 
We could perhaps add events that allow you to mix in external data when a tile has been loaded. 
Then you could pull the same area from another source. 
Or you go with a fully custom source, hosted by yourself. 
It will work but is a lot more trouble to set up and maintain.
I don't see, how Tangram and their tiles would get you further here.

**Comment by rbuch703** [comment] 2016-05-14 11:42
Yeah, scalibility is out of scope here. So if you have detailed questions on it just open a new issue.

So here's just a short answer: you're right, this approach by itself won't be scalable. I tried it with the ~500.000 buildings of Berlin, and there the mapping JSON file needed is already 33MB big. So the file size for all of Switzerland will probably be too much to handle for browsers.

Tiling the mapping file would be much better, but wouldn't currently work. The problem is that a `modifier` function only knows the building ID and building properties and needs to set the building color based only on those information. So your `modifier` wouldn't even know which mapping tile to load to get the additional information on a given building. I'm not quite sure, but I think you would run into pretty much the same problem with Tangram.

I think your best option for scalability is probably to add the desired information (either the distance to public transport, or even the modified color based on that distance) before it ever reaches the client. So you would have to set up a server that downloads the OSMBuildings GeoJSON tiles, parses the JSON contents and adds the information you want to add. You would then set up your OSMBuildings instance to use your GeoJSON tiles instead of using those from the OSMBuildings server. The advantage of this approach is that your server-side processing can be done in any programming language you want. but before you do that, please privately ask @kekscom for permission to use his GeoJSON tiles in this way (they are served from his private server).

For download, you essentially have two options: proxy and batch. For a proxying, you would write a server-side program that answers request from your web clients. Whenever a client requests a GeoJSON tile, your server program would download the corresponding GeoJSON tiles from the OSMBuildings servers, add the information from your mapping and then send it to the client. For batching, you would download all OSMBuildings GeoJSON tiles for Switzerland at once, add the desired information, and then put all of those files on a web server, from where your clients can then request them. 

Proxying is more complicated - especially writing the server component -, but requires much less server disk space. Batching is simple and not time-critical, as you are doing the mapping long before any client ever requests the data, but you'll need a server to hold all that data, and it will put a heavy strain on the OSMBuildings server while you download the tiles - so be sure to ask @kekscom for permission first.

**Comment by sevamoo** [comment] 2016-05-14 15:02
@kekscom @rbuch703  Thanks a lot. This was more informing than what I expected. 
I will update examples, if I managed to do new cases. 
Thanks again.

**Comment by kekscom** [comment] 2016-05-15 20:44
You're very welcome!

In brief about the OSM Buildings data service: downloading in bulk is not permitted.
For heavy usage or commercial purposes, there are other licensing options.

Otherwise proxying is totally fine and I'm going to add a small prototype in PHP soon.

**Closed** 2018-07-10 04:06 UTC

**Comment by Gideon1007** [comment] 2018-07-12 09:56
On updating the lat longs of another country like India (72.38,27.91) for ex. the map is not displayed on the screen. Need help on this . How can I render the buildings in 3d from a custom geojson file with lat longs from place other than Berlin.

**Comment by kekscom** [comment] 2018-07-12 12:09
This is not related to the issue.
Please open another one and provide example code of what you've tried.
For custom GeoJSON, please refer to documentation on https://osmbuildings.org
