### ISSUE TITLE
Map blinks on red when it's destroyed and created again

### ISSUE THREAD

**Issue by grayrattus** [OSMBuildings/OSMBuildings#201] opened 2020-04-13 11:51 UTC
https://codepen.io/grayrattus/pen/jObPKvw

Here is an example.

![image](https://user-images.githubusercontent.com/19289505/79118249-a88e9a00-7d8d-11ea-8666-04bb5cba18e8.png)

**Comment by kekscom** [comment] 2020-04-25 16:45
Confirmed. This seems caused by a few internal variables that can't easily be rebuild.
A solution would be a bigger rework which is currently out of scope.
Option 1. Don't destroy but rather hide the map container.
Option 2. Use an iframe.

**Closed** 2020-04-25 16:46 UTC
Labels: DEFECT

**Comment by mryellow** [comment] 2020-05-07 01:00
What was the resolution to this confirmed bug?

Why is it closed?

**Comment by mryellow** [comment] 2020-05-07 01:20
Is this confirmed bug honestly closed because it's "too hard"?

What are the plans for this software? Is it abandonware? Do you ever allow any bugs to be reported?

**Comment by mryellow** [comment] 2020-05-07 01:23
Is this confirmed bug closed because it's "too hard"?

What are the plans for this software?

It seems OSMBuildings.org have abandon all development on it, but why are they blocking the reporting of valid issues?

**Comment by mryellow** [comment] 2020-05-07 04:13
>  This seems caused by a few internal variables that can't easily be rebuild.

Which internal variables require re-factoring?

**Comment by Cobertos** [comment] 2020-10-20 00:50
This still seems to be an issue.

I don't see any particular variables that are being reused. All global state looks to be thrown away when creating a new instance so I'm not 100% sure what's going on. I call `destroy()` as well but I get issues related to https://github.com/OSMBuildings/OSMBuildings/issues/122 (and the proposed fix isn't really valid on master).

**Comment by Cobertos** [comment] 2020-10-20 01:15
Okay, this seems to be caused by the [lack of `setTimeout()` clearing in `destroy()` in the `View` class.](https://github.com/OSMBuildings/OSMBuildings/blob/6928ac5ef3785f269d615cb15302d64bddd700f5/src/view/index.js#L123)

As a workaround, you can track the ID of the setTimeout

```diff
< setTimeout(() => {
---
> this.renderTimeout = setTimeout(() => {
```

and clear it in destroy():

```diff
> clearTimeout(this.renderTimeout);
```

If you're using this workaround, you may as well also track the `requestionAnimationFrame()` and do a `cancelAnimationFrame()` so there's no rendering happening after all the resources are destroyed.
