### ISSUE TITLE
minZoom and maxZoom are clamped to >=14.5 and <=20 respectively

### ISSUE THREAD

**Issue by PeterVermont** [OSMBuildings/OSMBuildings#116] opened 2016-09-30 21:11 UTC
In the master head there are multiple places where minZoom is the **max** of the user's choice or 14.5.

Similarly, maxZoom is the **min** of user's choice or 20.

This effectively clamps zoom to be between 14.5 and 20. Is that What is desired?

On my map, 14.5 is not far out at all -- less than one cities worth.

By the way '14.5' and '20' are used in 12 places rather than a variable.

I understand that there might be limits and when I manually changed the code to allow minZoom to be less 14.5 it did not work lower than 14. Turned out that this was due to fixedZoom being set to 15 in addGeoJSONTiles. Even after changing this it did not draw although it was able to get all needed tiles (as far as I understood).

**Comment by kekscom** [comment] 2016-09-30 21:53
> This effectively clamps zoom to be between 14.5 and 20. Is that What is desired?
> On my map, 14.5 is not far out at all -- less than one cities worth.

Exactly. Zoom values lower than 14 cause massive tile loading and issues with horizon rendering.
Higher that 20 would be fine for me. Looks like 22 could be a useful limit.

> By the way '14.5' and '20' are used in 12 places rather than a variable.

Yes, that is very bad style and needs fixing.

> I understand that there might be limits and when I manually changed the code to allow minZoom to be less 14.5 it did not work lower than 14. Turned out that this was due to fixedZoom being set to 15 in addGeoJSONTiles. Even after changing this it did not draw although it was able to get all needed tiles (as far as I understood).

Not quite. fixedZoom just tells the backend what zoom the data is. Effectively setting the extent and data size of a tile. This should have no effect on visual representation.

**Comment by PeterVermont** [comment] 2016-10-03 14:00
Clamping the zoom makes this product unusable for my purposes. I can understand not showing buildings at a distant zoom but why kill the map entirely?

**Comment by rbuch703** [comment] 2016-10-03 18:17
Implementation limitations. IIRC, I wrote the frustum culler to first determine the set of all visible basemap tiles at some fixed zoom level (19?) for each frame, and then to merge tiles if appropriate. Merging takes care of loading and rendering only a reasonable number (< 200) of basemap tiles in each frame. This works as intended for close zoom levels. But if you zoom out too far, that initial set of all visible tiles can contain millions to billions of tiles (even though they will be merged down to a few hundred in the next step) and this becomes too slow to be usable. The hard-coded limit is in place to prevent those situations that may freeze the browser.

I wanted to replace this by a top-down approach (compute all visible tiles at zoom level 1, and subdivide as appropriate) for some time now, but never found the time to do so.

@kekscom: are there any other reasons, or would fixing this one issue enable OSMBuildings to zoom out all the way to level 0/1 (when the building layer is disabled)?

**Comment by rbuch703** [comment] 2016-10-03 18:29
Oh, right, I just remembered a few more issues (all of which are my fault :-/ ):

- The sky has a fixed height in meters, so when zooming out too far one would see the background color above the sky. This is probably not a show stopper, because a web developer could just force the camera angle to be steep enough for the sky not to be visible.
- due to the limited depth precision, there's a hard-coded maximum viewing distance (and fog distance) at about 7500 meters. Zoom out further and everything will just disappear. Now this *is* obviously a show stopper, and cannot quickly be fixed, because quite a bit of code depends on that limit.

**Comment by PeterVermont** [comment] 2016-10-03 20:54
I gave OSMBuildings a shot but have now switched to using [ViziCities](https://github.com/UDST/vizicities) which is working for my use case. Good luck and I'll re-visit your project some other time.

**Comment by kekscom** [comment] 2016-10-03 21:04
@rbuch I think you've outlined the cases.

**Closed by kekscom** 2016-10-03 21:04 UTC

**Comment by mryellow** [comment] 2020-05-07 01:13
> lower than 14 cause massive tile loading and issues with horizon rendering

I've found they work down to 12 or so.

> Higher that 20 would be fine for me. Looks like 22 could be a useful limit

So why is it limited?

> But if you zoom out too far, that initial set of all visible tiles can contain millions to billions of tiles (even though they will be merged down to a few hundred in the next step) and this becomes too slow to be usable. The hard-coded limit is in place to prevent those situations that may freeze the browser.

This should be up to the user.

> I wanted to replace this by a top-down approach (compute all visible tiles at zoom level 1, and subdivide as appropriate) for some time now, but never found the time to do so.

Then this issues should remain open and  @kekscom should stop closing all these valid tickets.

**Comment by mryellow** [comment] 2020-05-07 01:16
> Good luck and I'll re-visit your project some other time.

@PeterVermont Think I might have to go the same way. They keep closing tickets here for things which they've identified need improvement. Seems to be a reluctance to not only do more work on it, but to allow anyone else to improve it.

**Comment by kekscom** [comment] 2020-05-07 07:05
Please remember this is an open source project. Maintainers owe you nothing.
That said, it's always welcome to receive helpful comments, bug reports, pul requests and meaningful criticism too.
@mryellow While I see your intention you seem off acting respectful and politely.
Your'e code ides are partially incorrect or pointless, your'e refusing to think through current solution and most recently are recommending  code changes that harm our infrastructure. This is no longer acceptable.
